services:
  db:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - tradingapp-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tradingapp-pg-local:
